apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::097003440739:role/eksctl-roboshop-nodegroup-roboshop                                                                -NodeInstanceRole-1JprawXoK56G
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::097003440739:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-08-06T06:00:16Z"
  name: aws-auth
  namespace: kube-system
  uid: 5aeb8fc8-c2f3-43aa-8b23-4dd763910bef
